spring:
  application:
    name: api-service
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: chandu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: event_booking_group_1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.beans.factory: DEBUG
    org.springframework.kafka: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka

jwt:
  secret: "UEtB2vXTuLygAfxK36RrZABJHWIasP/iA14mT0Q7BDuMM4CDCFi4egUBzc1Ytepc0cb4xhDIDh/AOAif8k8t7g=="
