spring:
  application:
    name: discovery-service

server:
  port: 8084
  host: localhost

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${server.host}:${server.port}/eureka
