spring:
  application:
    name: bookings
  datasource:
    url: jdbc:mysql://localhost:3306/bookings
    username: root
    password: chandu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: event_booking_group_1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8081

eurka:
  client:
    server-url:
      defaultZone: http://${server.host:localhost}/8084/euraka

logging:
  level:
    org.springframework.kafka: DEBUG
